project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"
  

website:
  title: "Zeineb chekir"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Contact
        contents:
          - zeinebchekir742@gmail.com
          - https://github.com/zeinebchekir
         
      
format:
  html:
    theme: cosmo
    css: thpe.css
    toc: true
    number-sections: true
    #embed-resources: true
bibliography: bib.bib
csl: apa.csl

execute:
  freeze: auto