{
  "hash": "100f833926a6ad72d07f83ff5f57ffb2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploration statistique de la violence domestique envers les femmes à partir de données sociales\"\ndate: '2025-12-27'\nformat: \n  html:\n    output-file: \"index.html\"\n---\n\n\n\n\n\n# Introduction\nLa violence domestique envers les femmes est un problème social majeur dans de nombreux pays, affectant gravement la santé physique, psychologique et sociale des victimes. Comprendre les facteurs qui contribuent à cette violence est essentiel pour développer des stratégies de prévention efficaces et des politiques adaptées.\n\nCe projet vise à analyser statistiquement un dataset portant sur la violence domestique dans une zone rurale d’un pays en développement.\n\nL’objectif principal est d’explorer les corrélations entre ces facteurs et l’expérience de la violence domestique, afin d’identifier les profils les plus à risque et de fournir des insights pertinents pour la prise de décision et la sensibilisation sur ce problème social. Cette analyse permettra également de mettre en lumière l’importance de l’éducation, de l’emploi et du statut marital dans la vulnérabilité des femmes face à la violence domestique.\n\n# Déscription de la dataset\n\nLe dataset étudié concerne la violence domestique à l’encontre des femmes. Les données ont été extraites d’une enquête menée auprès de femmes dans une région rurale d’un pays en développement et sont disponibles sur Kaggle. Le dataset comprend 347 observations, incluant à la fois des femmes ayant subi des violences et des femmes n’en ayant pas été victimes. Les variables recueillies sont de nature socio-économique et démographique, telles que l’âge, le niveau d’éducation, le statut marital, l’emploi et le revenu des répondantes. Le tableau suivant présente la liste des colonnes ainsi que leurs désignations respectives.\n<table class=\"table table-striped\">\n<caption>Description du dataset de violence domestique</caption>\n<thead>\n<tr>\n<th>Variable</th>\n<th>Type</th>\n<th>Description</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>SL.No</td>\n<td>Numérique</td>\n<td>Numéro de l'enregistrement</td>\n</tr>\n<tr>\n<td>Age</td>\n<td>Numérique</td>\n<td>Âge de la répondante</td>\n</tr>\n<tr>\n<td>Education</td>\n<td>Catégorie</td>\n<td>Niveau d'éducation (None, Primary, Secondary, Tertiary)</td>\n</tr>\n<tr>\n<td>Employment</td>\n<td>Catégorie</td>\n<td>Statut professionnel (unemployed,semi employed,employed.)</td>\n</tr>\n<tr>\n<td>Income</td>\n<td>Numérique</td>\n<td>Revenu de la répondante (0 = aucun revenu)</td>\n</tr>\n<tr>\n<td>Marital status</td>\n<td>Catégorie</td>\n<td>Statut marital (Married, Unmarried)</td>\n</tr>\n<tr>\n<td>Violence</td>\n<td>Catégorie</td>\n<td>Si la répondante a subi des violences domestiques (Yes / No)</td>\n</tr>\n</tbody>\n</table>\n\n## Statistique générale du dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcul des statistiques de base\nstats_violence <- function(data) {\n  # Standardiser les valeurs (Yes/yes)\n  data$Violence_clean <- ifelse(tolower(data$Violence) %in% c(\"yes\", \"oui\", \"y\"), \"Yes\", \"No\")\n  \n  nb_yes <- sum(data$Violence_clean == \"Yes\", na.rm = TRUE)\n  nb_no <- sum(data$Violence_clean == \"No\", na.rm = TRUE)\n  nb_total <- nrow(data)\n  percent_yes <- (nb_yes / nb_total) * 100\n  \n  return(list(\n    nb_yes = nb_yes,\n    nb_no = nb_no,\n    nb_total = nb_total,\n    percent_yes = percent_yes\n  ))\n}\n\n# Calculer les statistiques\nstats <- stats_violence(dv)\n\n# Créer un dataframe pour l'affichage\nstats_df <- data.frame(\n  Statistic = c(\"Nombre total d'observations\", \n                \"Nombre de victimes (Yes)\", \n                \"Nombre de non-victimes (No)\",\n                \"Pourcentage de victimes\",\n                \"Proportion de victimes\"),\n  Value = c(\n    stats$nb_total,\n    stats$nb_yes,\n    stats$nb_no,\n    paste0(round(stats$percent_yes, 1), \"%\"),\n    round(stats$nb_yes / stats$nb_total, 3)\n  ),\n  Description = c(\n    \"Nombre total de femmes interrogées\",\n    \"Femmes ayant déclaré subir des violences domestiques\",\n    \"Femmes n'ayant pas déclaré de violences domestiques\",\n    \"Pourcentage de femmes victimes de violence\",\n    \"Ratio victimes/total\"\n  )\n)\n\n# Afficher les résultats\ncat(\"=== STATISTIQUES SUR LA VIOLENCE DOMESTIQUE ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== STATISTIQUES SUR LA VIOLENCE DOMESTIQUE ===\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(stats_df, caption = \"Statistiques descriptives sur la violence domestique\") \n```\n\n::: {.cell-output-display}\n\n\nTable: Statistiques descriptives sur la violence domestique\n\n|Statistic                   |Value |Description                                          |\n|:---------------------------|:-----|:----------------------------------------------------|\n|Nombre total d'observations |347   |Nombre total de femmes interrogées                   |\n|Nombre de victimes (Yes)    |86    |Femmes ayant déclaré subir des violences domestiques |\n|Nombre de non-victimes (No) |261   |Femmes n'ayant pas déclaré de violences domestiques  |\n|Pourcentage de victimes     |24.8% |Pourcentage de femmes victimes de violence           |\n|Proportion de victimes      |0.248 |Ratio victimes/total                                 |\n\n\n:::\n\n```{.r .cell-code}\n# Visualisation\nviolence_dist <- data.frame(\n  Statut = c(\"Victimes\", \"Non-victimes\"),\n  Count = c(stats$nb_yes, stats$nb_no),\n  Pourcentage = c(stats$percent_yes, 100 - stats$percent_yes)\n)\n# Graphique 1: Diagramme en barres\np1 <- ggplot(violence_dist, aes(x = Statut, y = Count, fill = Statut)) +\n  geom_bar(stat = \"identity\", width = 0.6) +\n  geom_text(aes(label = paste0(Count, \"\\n(\", round(Pourcentage, 1), \"%)\")), \n            vjust = -0.5, size = 4) +\n  scale_fill_manual(values = c(\"Victimes\" = \"#e74c3c\", \"Non-victimes\" = \"#2ecc71\")) +\n  labs(title = \"Distribution des victimes de violence domestique\",\n       subtitle = paste(\"Total:\", stats$nb_total, \"observations\"),\n       x = \"\", y = \"Nombre de femmes\") +\n  theme_minimal(base_size = 14) +\n  theme(legend.position = \"none\")\n\n# Graphique 2: Diagramme circulaire\np2 <- ggplot(violence_dist, aes(x = \"\", y = Pourcentage, fill = Statut)) +\n  geom_bar(stat = \"identity\", width = 1) +\n  coord_polar(\"y\", start = 0) +\n  scale_fill_manual(values = c(\"Victimes\" = \"#e74c3c\", \"Non-victimes\" = \"#2ecc71\")) +\n  geom_text(aes(label = paste0(round(Pourcentage, 1), \"%\")), \n            position = position_stack(vjust = 0.5), size = 5) +\n  labs(title = \"Répartition en pourcentage\",\n       fill = \"Statut\") +\n  theme_void(base_size = 14) +\n  theme(legend.position = \"bottom\")\n\n# Afficher les graphiques côte à côte\nlibrary(gridExtra)\ngrid.arrange(p1, p2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n# Analyse exploratoire des données\n##  Statistiques d'âge par statut de violence\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndv <- dv %>%\nmutate(AgeGroup = case_when(\nAge >= 15 & Age <= 24 ~ \"15-24\",\nAge >= 25 & Age <= 34 ~ \"25-34\",\nAge >= 35 & Age <= 44 ~ \"35-44\",\nAge >= 45 ~ \"45+\",\nTRUE ~ NA_character_\n))\nhead(dv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SL..No Age Education Employment Income Marital.status Violence AgeGroup\n1      1  30 secondary unemployed      0        married      yes    25-34\n2      2  47  tertiary unemployed      0        married       no      45+\n3      3  24  tertiary unemployed      0       unmarred       no    15-24\n4      4  22  tertiary unemployed      0       unmarred       no    15-24\n5      5  50   primary unemployed      0        married      yes      45+\n6      6  21  tertiary unemployed      0       unmarred      yes    15-24\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndv <- dv %>%\n  mutate(AgeGroup = case_when(\n    Age >= 15 & Age <= 24 ~ \"15-24\",\n    Age >= 25 & Age <= 34 ~ \"25-34\",\n    Age >= 35 & Age <= 44 ~ \"35-44\",\n    Age >= 45 ~ \"45+\",\n    TRUE ~ NA_character_\n  ))\n\n# Résumé par tranche d'âge et violence\nsummary_age <- dv %>%\n  group_by(AgeGroup, Violence) %>%\n  summarise(Count = n(), .groups = \"drop\")\n\n# Calcul du pourcentage de victimes par tranche d'âge\npercent_victims <- summary_age %>%\n  group_by(AgeGroup) %>%\n  mutate(\n    Total = sum(Count),\n    Percent = Count / Total * 100\n  ) %>%\n  filter(Violence == \"yes\") \n\nggplot(summary_age, aes(x = AgeGroup, y = Count, fill = Violence)) +\n  geom_bar(stat = \"identity\") +\n\n  # Ajouter le pourcentage des victimes\n  geom_text(\n    data = percent_victims,\n    aes(\n      x = AgeGroup,\n      y = Total,\n      label = paste0(round(Percent, 1), \"% victimes\")\n    ),\n    vjust = -0.5,\n    size = 4\n  ) +\n\n  scale_fill_manual(\n    values = c(\"yes\" = \"red\", \"no\" = \"steelblue\"),\n    labels = c(\"Non victimes\", \"Victimes\")\n  ) +\n\n  labs(\n    title = \"Violence domestique par tranche d'âge\",\n    subtitle = \"Pourcentage de victimes indiqué au-dessus de chaque groupe\",\n    x = \"Tranche d'âge\",\n    y = \"Nombre de femmes\",\n    fill = \"Statut\"\n  ) +\n\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndv$Violence <- factor(dv$Violence,\n                        levels = c(\"no\", \"yes\"),\n                        labels = c(\"no\", \"yes\"))\nggplot(dv, aes(x = Age, fill = Violence, color = Violence)) +\n  geom_histogram(aes(y = ..density..),\n                 position = \"identity\",\n                 bins = 15,\n                 alpha = 0.3) +\n  geom_density(alpha = 0.6, linewidth = 1) +\n  labs(\n    title = \"Histogramme et densité de l'âge selon la violence domestique\",\n    x = \"Âge\",\n    y = \"Densité\",\n    fill = \"Violence domestique\",\n    color = \"Violence domestique\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nL’analyse de la distribution de l’âge montre que les femmes victimes de violence domestique sont réparties sur une plage d’âge plus large que les non victimes. Alors que les femmes non victimes sont majoritairement concentrées entre 20 et 30 ans, les victimes présentent une distribution étendue jusqu’à 50 ans et plus. Cela suggère que l’âge, bien qu’informatif, ne constitue pas à lui seul un facteur discriminant, mais pourrait interagir avec d’autres variables socio-économiques et familiales.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dv, aes(x = Violence, y = Age, fill = Violence)) +\n  geom_boxplot(alpha = 0.6) +\n  labs(\n    title = \"Boxplot de l'âge selon la violence domestique\",\n    x = \"Violence domestique\",\n    y = \"Âge\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nLe boxplot montre que la médiane d’âge des femmes ayant déclaré des violences domestiques est légèrement plus élevée que celle des femmes n’en ayant pas déclaré, indiquant que les femmes victimes sont en moyenne plus âgées ,Par ailleurs 50 % des femmes non-victimes ont un âge compris entre 23 et 35 ans, tandis que 50 % des victimes ont un âge compris entre 25 et 44 ans. Le chevauchement des boîtes entre 25 et 35 ans indique que certaines femmes de cette tranche d’âge sont présentes dans les deux groupes, ce qui suggère que l’âge seul ne constitue pas un facteur explicatif suffisant de la violence domestique.\n\n## Statistiques d'educations par status de violence \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_pie <- dv %>%\n  group_by(Education, Violence) %>%\n  summarise(Count = n(), .groups = 'drop') %>%\n  group_by(Education) %>%\n  mutate(Pct = Count / sum(Count) * 100)\nggplot(df_pie, aes(x = \"\", y = Pct, fill = Violence)) +\n  geom_bar(stat = \"identity\", width = 1) +\n  coord_polar(theta = \"y\") +\n  geom_text(aes(label = paste0(round(Pct,1), \"%\")),\n            position = position_stack(vjust = 0.5)) +\n  facet_wrap(~Education) +\n  labs(title = \"Répartition des femmes victimes et non-victimes par niveau d’éducation\") +\n  theme_void() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nInterprétation :\nL’analyse montre que les femmes ayant un niveau d’éducation primaire présentent la plus forte proportion de victimes de violence au sein de leur groupe.\nÀ l’inverse, les femmes ayant un niveau secondaire ou tertiaire ont une proportion de victimes plus faible, ce qui suggère que le risque de violence diminue avec le niveau d’éducation.\n\n## Statistiques de status d'emploi par status de violence \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tableau croisé Employment × Violence\nemploi_violence <- dv %>%\n  group_by(Employment, Violence) %>%\n  summarise(\n    Effectif = n(),\n    .groups = 'drop'\n  ) %>%\n  group_by(Employment) %>%\n  mutate(\n    Total_categorie = sum(Effectif),\n    Pourcentage_categorie = (Effectif / Total_categorie) * 100\n  ) %>%\n  ungroup() %>%\n  mutate(\n    Pourcentage_total = (Effectif / sum(Effectif)) * 100\n  ) %>%\n  arrange(Employment, desc(Violence))\n\n# Afficher le tableau complet\ncat(\"=== TABLEAU CROISÉ EMPLOI × VIOLENCE ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== TABLEAU CROISÉ EMPLOI × VIOLENCE ===\n```\n\n\n:::\n\n```{.r .cell-code}\nkable(emploi_violence, digits = 1,\n      caption = \"Répartition de la violence domestique par statut d'emploi\",\n      col.names = c(\"Statut emploi\", \"Victime violence\", \"Effectif\", \n                    \"Total catégorie\", \"% dans catégorie\", \"% du total\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Répartition de la violence domestique par statut d'emploi\n\n|Statut emploi |Victime violence | Effectif| Total catégorie| % dans catégorie| % du total|\n|:-------------|:----------------|--------:|---------------:|----------------:|----------:|\n|employed      |yes              |        6|              26|             23.1|        1.7|\n|employed      |no               |       20|              26|             76.9|        5.8|\n|semi employed |yes              |        5|              47|             10.6|        1.4|\n|semi employed |no               |       42|              47|             89.4|       12.1|\n|unemployed    |yes              |       75|             274|             27.4|       21.6|\n|unemployed    |no               |      199|             274|             72.6|       57.3|\n\n\n:::\n\n```{.r .cell-code}\n  # Calcul du taux de violence par statut d'emploi\ntaux_violence_emploi <- emploi_violence %>%\n  filter(Violence == \"yes\") %>%\n  select(Employment, Effectif, Total_categorie, Pourcentage_categorie) %>%\n  rename(\n    \"Nombre victimes\" = Effectif,\n    \"Total groupe\" = Total_categorie,\n    \"Taux violence (%)\" = Pourcentage_categorie\n  ) %>%\n  arrange(desc(`Taux violence (%)`))\n\n \n# Répartition emploi/chômage parmi les victimes\nvictimes_only <- dv %>%\n  filter(Violence == \"yes\")\n\nrepartition_victimes <- victimes_only %>%\n  group_by(Employment) %>%\n  summarise(\n    Nombre = n(),\n    Pourcentage = (n() / nrow(victimes_only)) * 100\n  ) %>%\n  arrange(desc(Pourcentage))\n\n# Diagramme 2: Barplot empilé\np2 <- ggplot(emploi_violence, \n             aes(x = Employment, y = Effectif, fill = Violence)) +\n  geom_bar(stat = \"identity\", position = \"fill\") +\n  geom_text(aes(label = paste0(round(Pourcentage_categorie, 1), \"%\")),\n            position = position_fill(vjust = 0.5), \n            size = 4, color = \"white\", fontface = \"bold\") +\n  scale_fill_manual(values = c(\"yes\" = \"#e74c3c\", \"no\" = \"#2ecc71\"),\n                    name = \"Victime de violence\") +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(title = \"Répartition violence/non-violence par statut d'emploi\",\n       subtitle = \"Proportion relative dans chaque catégorie\",\n       x = \"Statut d'emploi\", y = \"Proportion\") +\n  theme_minimal(base_size = 14) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n\n\n# Diagramme 3: Répartition parmi les victimes\np3 <- ggplot(repartition_victimes, \n             aes(x = reorder(Employment, -Pourcentage), \n                 y = Pourcentage, \n                 fill = Employment)) +\n  geom_bar(stat = \"identity\", alpha = 0.8) +\n  geom_text(aes(label = paste0(round(Pourcentage, 1), \"%\\n(n=\", Nombre, \")\")), \n            vjust = -0.5, size = 4) +\n  scale_fill_brewer(palette = \"Set3\", name = \"Statut d'emploi\") +\n  labs(title = \"Répartition des victimes par statut d'emploi\",\n       subtitle = paste(\"Total victimes:\", nrow(victimes_only)),\n       x = \"Statut d'emploi\", y = \"Pourcentage des victimes (%)\") +\n  theme_minimal(base_size = 14) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1),\n        legend.position = \"none\") +\n  ylim(0, max(repartition_victimes$Pourcentage) * 1.2)\n\n# Afficher les graphiques\np2\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\np3\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Test statistique : Chi-carré\ntable_chi <- table(dv$Employment, dv$Violence)\nchi_test <- chisq.test(table_chi)\n\ncat(\"=== TEST DU CHI-CARRÉ (Emploi × Violence) ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== TEST DU CHI-CARRÉ (Emploi × Violence) ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Tableau de contingence:\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTableau de contingence:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table_chi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                 no yes\n  employed       20   6\n  semi employed  42   5\n  unemployed    199  75\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nRésultats du test:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRésultats du test:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Statistique Chi²:\", round(chi_test$statistic, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStatistique Chi²: 6.07 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Degrés de liberté:\", chi_test$parameter, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDegrés de liberté: 2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Valeur-p:\", format.pval(chi_test$p.value, digits = 3), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nValeur-p: 0.0481 \n```\n\n\n:::\n\n```{.r .cell-code}\nif(chi_test$p.value < 0.05) {\n  cat(\"→ Conclusion: Il existe une association SIGNIFICATIVE entre\\n\")\n  cat(\"   le statut d'emploi et la violence domestique (p < 0.05).\\n\")\n} else {\n  cat(\"→ Conclusion: Aucune association significative n'a été détectée\\n\")\n  cat(\"   entre le statut d'emploi et la violence domestique (p > 0.05).\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n→ Conclusion: Il existe une association SIGNIFICATIVE entre\n   le statut d'emploi et la violence domestique (p < 0.05).\n```\n\n\n:::\n:::\n\nL’analyse révèle que les femmes au chômage concentrent la majorité des cas de violence, représentant 87 % de l’ensemble des femmes victimes. Par ailleurs, la proportion de victimes rapportée à l’effectif total de ce groupe est également la plus élevée de 27% , indiquant que l’emploi pourrait jouer un rôle protecteur vis-à-vis de l’exposition à la violence.\n\n## Statistique  de revenue par status de violence \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\ndv %>%\n  group_by(Violence) %>%\n  summarise(\n    moyenne = mean(Income, na.rm = TRUE),\n    mediane = median(Income, na.rm = TRUE),\n    ecart_type = sd(Income, na.rm = TRUE),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  Violence moyenne mediane ecart_type     n\n  <fct>      <dbl>   <dbl>      <dbl> <int>\n1 no         2505.       0      6296.   261\n2 yes         915.       0      3331.    86\n```\n\n\n:::\n:::\n\nLe tableau montre les statistiques descriptives du revenu des femmes selon qu’elles ont été victimes de violence (yes) ou non (no) :\n\nRevenu moyen : Les femmes victimes de violence ont un revenu moyen (915) beaucoup plus faible que celles qui n’ont pas été victimes (2505), suggérant que les victimes tendent à avoir des revenus plus bas.\n\nMédiane : La médiane est de 0 pour les deux groupes, ce qui indique que la moitié des femmes dans chaque groupe a un revenu nul ou très faible.\n\nÉcart-type : La dispersion des revenus est plus grande pour les femmes non victimes (6296) que pour les victimes (3331), ce qui montre que le revenu des non victimes varie davantage.\n\nEffectifs (n) : Le groupe des femmes non victimes est plus nombreux (261) que celui des victimes (86).\n## Statisqtique des femmes avec emploi ou semi-emploi et le revenu avec le status de violence \n\n::: {.cell}\n\n```{.r .cell-code}\ndv <- dv %>%\n  mutate(tranche_revenu = case_when(\n    Income >= 0 & Income <8  ~ \"0k\",\n    Income >=8 & Income <=1000 ~ \"8-1K\",\n    Income > 1000 & Income<= 6000   ~ \"1k-6k\",\n    Income > 6000   & Income <= 8000  ~ \"6k-8k\",\n    Income > 8000  & Income <= 10000  ~ \"8k-10k\",\n    Income > 10000  & Income <= 15000  ~ \"10k-15k\",\n    Income > 15000  & Income <= 20000  ~ \"15k-20k\",\n    Income > 20000   & Income <= 30000 ~ \"20k-30k\",                   Income >30000 ~ \">30k\",\n    TRUE                               ~ NA_character_   # valeurs manquantes ou négatives\n  ))\ndv$tranche_revenu <- factor(dv$tranche_revenu,\n                            levels = c(\"0k\", \"8-1K\", \n                                       \"1k-6k\", \"6k-8k\", \"8k-10k\", \"10k-15k\", \n                                       \"15k-20k\", \"20k-30k\", \">30k\"))\n\n# Pourcentage de victimes dans chaque tranche de revenu\nsummary_revenu <- dv %>%\n  group_by(tranche_revenu) %>%\n  summarise(\n    total = n(),\n    victimes = sum(Violence == \"yes\"),\n    pct_victimes = victimes / total * 100\n  )\n\nsummary_revenu\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 4\n  tranche_revenu total victimes pct_victimes\n  <fct>          <int>    <int>        <dbl>\n1 0k               272       75        27.6 \n2 8-1K               3        0         0   \n3 1k-6k             39        7        17.9 \n4 6k-8k              5        2        40   \n5 8k-10k             5        0         0   \n6 10k-15k            6        1        16.7 \n7 15k-20k            2        0         0   \n8 20k-30k           14        1         7.14\n9 >30k               1        0         0   \n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(summary_revenu, aes(x = tranche_revenu, y = pct_victimes, fill = tranche_revenu)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = paste0(round(pct_victimes,1), \"%\")), vjust = -0.5) +\n  labs(title = \"Pourcentage de victimes selon la tranche de revenu\",\n       x = \"Tranche de revenu\", y = \"Pourcentage de victimes (%)\") +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n        axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Tableau croisé\ntab <- table(dv$tranche_revenu, dv$Violence)\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n           no yes\n  0k      197  75\n  8-1K      3   0\n  1k-6k    32   7\n  6k-8k     3   2\n  8k-10k    5   0\n  10k-15k   5   1\n  15k-20k   2   0\n  20k-30k  13   1\n  >30k      1   0\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  tab\nX-squared = 8.9077, df = 8, p-value = 0.3501\n```\n\n\n:::\n:::\n\nUne p-value de 0,526 indique qu’il n’existe pas de preuve statistiquement significative montrant que le revenu (tranche_revenu) influence le fait d’être victime de violence.\nMême si certaines tranches de revenu présentent un pourcentage de victimes légèrement plus élevé ou plus faible, ces différences peuvent simplement résulter du hasard.\nAinsi, le revenu, considéré seul selon les tranches définies, ne semble pas être un facteur déterminant du taux de violence dans ce dataset.\n\n## Statistique par status marital \n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dv$Marital.status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n married unmarred \n     300       47 \n```\n\n\n:::\n\n```{.r .cell-code}\ndv_pct <- dv %>%\n  group_by(Marital.status, Violence) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  group_by(Marital.status) %>%\n  mutate(pct = count / sum(count) * 100)\n\n# Barplot avec pourcentages\nggplot(dv_pct, aes(x = Marital.status, y = pct, fill = Violence)) +\n  geom_bar(stat = \"identity\", position = \"fill\") +\n  geom_text(aes(label = paste0(round(pct,1), \"%\")), \n            position = position_fill(vjust = 0.5), color = \"white\", fontface = \"bold\") +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(title = \"Proportion de victimes selon le statut marital\",\n       x = \"Statut marital\", y = \"Pourcentage\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nLes femmes mariées ont une proportion de victimes beaucoup plus élevée de 27.7% que les femmes non mariées .\nCela suggère que le statut marital, et particulièrement le mariage, est associé à un risque plus élevé de violence\nLes barres représentant les femmes non mariées sont plus dominées par la catégorie “non victimes”, indiquant un risque plus faible.\n\n\n## Revenu × Statut marital × Violence\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dv, aes(x = tranche_revenu, fill = Violence)) +\n  geom_bar(position = \"fill\") +\n  facet_wrap(~ Marital.status) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"Violence selon le revenu et le statut marital\",\n       x = \"Tranche de revenu\", y = \"Proportion\")\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n### Âge × Statut marital × Violence (âge contextuel)\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dv, aes(x = AgeGroup, fill = Violence)) +\n  geom_bar(position = \"fill\") +\n  facet_wrap(~ Marital.status) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"Violence selon l’âge et le statut marital\",\n       x = \"Tranche d’âge\", y = \"Proportion\")\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nFemmes mariées:\nLa violence touche toutes les tranches d’âge, ce qui montre que le risque n’est pas limité à une tranche spécifique.\nLa proportion la plus élevée se situe dans la tranche >45 ans, suggérant que les femmes plus âgées mariées sont particulièrement exposées.\nCela peut refléter une exposition cumulative au fil du temps ou des facteurs liés à la durée du mariage.\nFemmes non mariées:\nLe pourcentage de victimes reste relativement faible, inférieur à 10% pour la tranche 15-24 ans.\nCela indique que le mariage est associé à un risque accru de violence, alors que les femmes célibataires, divorcées ou veuves présentent des proportions beaucoup plus faibles.\n\n### status marital x emploi\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_me <- table(dv$Marital.status, dv$Employment)\ntab_me\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \n           employed semi employed unemployed\n  married        24            36        240\n  unmarred        2            11         34\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(tab_me, margin = 1) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \n            employed semi employed unemployed\n  married   8.000000     12.000000  80.000000\n  unmarred  4.255319     23.404255  72.340426\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\n\nheat_data <- dv %>%\n  group_by(Employment, Marital.status) %>%\n  summarise(\n    pct_victimes = mean(Violence == \"yes\") * 100,\n    .groups = \"drop\"\n  )\n\nggplot(heat_data, aes(x = Employment, y = Marital.status, fill = pct_victimes)) +\n  geom_tile(color = \"white\") +\n  geom_text(aes(label = paste0(round(pct_victimes,1), \"%\")), color = \"black\") +\n  scale_fill_gradient(low = \"#f0f0f0\", high = \"#d73027\") +\n  labs(\n    title = \"Heatmap du taux de violence selon l’emploi et le statut marital\",\n    x = \"Statut d’emploi\",\n    y = \"Statut marital\",\n    fill = \"% victimes\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](domesticviolence_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nLes proportions de victimes sont nettement plus élevées, quel que soit le statut d’emploi :\n\nEmploi : 25%\n\nSemi-emploi : 13,9%\n\nChômage : 30%\n\nLes femmes mariées au chômage sont donc le groupe le plus vulnérable, avec un risque de violence presque triple par rapport aux femmes non mariées au chômage.\n\nMême les femmes mariées ayant un emploi ou un semi-emploi présentent des proportions plus élevées que leurs homologues non mariées, ce qui suggère que le mariage est associé à un risque accru, indépendamment de l’emploi.\n\n\n\n",
    "supporting": [
      "domesticviolence_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}